spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/mydb
    username: myadmin
    password: 515608
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8086

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace
    com:
      voiceofsiren: debug
